In [1]:
import numpy as np
import math

#### Problem 2

#### 1.

In [2]:
def p(x):
    return x**2.+(9.**12.)*x-3.

In [3]:
r = (-9.**12. + math.sqrt(9.**24.+12.))/2.
r_approx = 6./((9.**12.)+math.sqrt((9.**12.)**2.+12.))
print(p(r))
print(p(r_approx))

-3.0
0.0


#### 2.

In [4]:
r_approx

1.062211848441645e-11

#### 3.

In [5]:
back_err = abs(p(r_approx))
back_err

0.0

#### 5.

In [6]:
r

0.0

#### Problem 3

#### 1.

In [7]:
def p_exp(x):
    x=float(x)
    return x**20 - 210*x**19 + 20615*x**18 - 1256850*x**17 + 53327946*x**16 - 1672280820*x**15 + 40171771630*x**14 - \
    756111184500*x**13 + 11310276995381*x**12 - 135585182899530*x**11 + 1307535010540395*x**10 - \
    10142299865511450*x**9 + 63030812099294896*x**8 - 311333643161390640*x**7 + 1206647803780373360*x**6 - \
    3599979517947607200*x**5 + 8037811822645051776*x**4 - 12870931245150988800*x**3 + 13803759753640704000*x**2 - 8752948036761600000*x + 2432902008176640000

In [8]:
r = 16
p_exp(16)

-6029312000.0

It's probably due to rounding errors and cancellations that floating point arithmetic introduces as the number starts to reach 64 bits.

#### 2.

In [9]:
def bisect_once(f,a,b):
    if f(a) >= 0:
        raise Exception("f(a) must be less than zero!")
    elif f(b) <= 0:
        raise Exception("f(b) must be greater than zero!")
    if f((a+b)/2) < 0: 
        c = (a+b)/2
        d=b
        root = False 
    elif f((a+b)/2) >0:
        c=a
        d = (a+b)/2 
        root = False
    else:
        c = (a+b)/2
        d = (a+b)/2
        root = True
    return c,d,root

In [10]:
N=50
a0=15.9
b0=16.1
avals=np.zeros(N)
bvals=np.zeros(N)
avals[0]=a0
bvals[0]=b0
for n in range(1,N):
    avals[n],bvals[n],root=bisect_once(p_exp,avals[n-1],bvals[n-1])
    if root:
        break
avals, bvals

(array([15.9       , 16.        , 16.        , 16.        , 16.        ,
        16.        , 16.003125  , 16.003125  , 16.003125  , 16.003125  ,
        16.00332031, 16.00332031, 16.00332031, 16.00332031, 16.00332031,
        16.00332642, 16.00332642, 16.00332794, 16.00332794, 16.00332832,
        16.00332832, 16.00332842, 16.00332847, 16.00332849, 16.00332849,
        16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 ,
        16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 ,
        16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 ,
        16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 ,
        16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 , 16.0033285 ]),
 array([16.1       , 16.1       , 16.05      , 16.025     , 16.0125    ,
        16.00625   , 16.00625   , 16.0046875 , 16.00390625, 16.00351562,
        16.00351562, 16.00341797, 16.00336914, 16.00334473, 16.00333252,
        16.00333252, 16.00332947, 16.00332947, 16

In [11]:
fwd_err = abs(avals[-1]-r)
back_err = abs(p_exp(r))
print('Forward Error:', fwd_err)
print('Backward Error:', back_err)

Forward Error: 0.0033284982507311156
Backward Error: 6029312000.0


#### 3.

In [12]:
def p(x):
    y = 1
    for i in range(1,21):
        y *= (x-i)
    return y

In [13]:
N=50
a0=15.9
b0=16.1
avals=np.zeros(N)
bvals=np.zeros(N)
avals[0]=a0
bvals[0]=b0
for n in range(1,N):
    avals[n],bvals[n],root=bisect_once(p,avals[n-1],bvals[n-1])
    if root:
        break
avals, bvals

(array([15.9, 16. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ]),
 array([16.1, 16. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ]))

In [14]:
fwd_err = abs(next((x for x in reversed(avals) if x != 0), 0) - r)
print('Forward Error:', fwd_err)

Forward Error: 0.0
